Repository aleinin/game-of-the-year, pull requests merged in 2020-12, with the labels that each got.

#7 Add endpoint to fetch all submissions
  goty-server/src/main/java/com/aleinin/goty/submit/SubmissionController.kt
Labels: backend, enhancement

#6 Refactor app state
  goty-client/src/api/app/app.guard.ts
  goty-client/src/api/app/app.step.service.ts
  goty-client/src/api/app/app.store.ts
  goty-client/src/api/constants.ts
  goty-client/src/api/ui/ui.guard.ts
  goty-client/src/api/ui/ui.service.ts
  goty-client/src/api/ui/ui.store.ts
  goty-client/src/app/app-routing.module.ts
  goty-client/src/app/app.component.scss
  goty-client/src/app/form/form.component.ts
  goty-client/src/app/form/game-of-the-year/game-of-the-year.component.ts
  goty-client/src/app/recovery/recovery.component.ts
  goty-client/src/app/start-page/start-page.component.ts
Labels: frontend

#14 #10 Add results calculation and endpoint
  goty-server/src/main/kotlin/com/aleinin/goty/result/GameRankingService.kt
  goty-server/src/main/kotlin/com/aleinin/goty/result/GameScoringService.kt
  goty-server/src/main/kotlin/com/aleinin/goty/result/PointsService.kt
  goty-server/src/main/kotlin/com/aleinin/goty/result/RankedGameResult.kt
  goty-server/src/main/kotlin/com/aleinin/goty/result/ResultController.kt
  goty-server/src/main/kotlin/com/aleinin/goty/result/ResultResponse.kt
  goty-server/src/main/kotlin/com/aleinin/goty/result/ResultService.kt
  goty-server/src/main/kotlin/com/aleinin/goty/result/ScoredGameResult.kt
Labels: backend

#16 #15 Fix Spring Data MongoDB properties being ignored
  goty-server/src/main/kotlin/com/aleinin/goty/mongo/MongoClientConfiguration.kt
  goty-server/src/main/kotlin/com/aleinin/goty/mongo/MongoConfiguration.kt
Labels: backend, bug

#21 Fix controls on mobile
  goty-client/src/app/submission/info/info.component.scss
  goty-client/src/app/submission/list-item/list-item.component.scss
Labels: bug, frontend

#20 Simplify Guard. UI => SubmissionFlow, remove final traces of 'form'
  goty-client/src/api/submission-flow/submission-flow.guard.ts
  goty-client/src/api/submission-flow/submission-flow.service.ts
  goty-client/src/api/submission-flow/submission-flow.store.ts
  goty-client/src/api/ui/ui.guard.ts
  goty-client/src/api/ui/ui.service.ts
  goty-client/src/api/ui/ui.store.ts
  goty-client/src/app/app-routing.module.ts
  goty-client/src/app/recovery/recovery.component.ts
  goty-client/src/app/start-page/start-page.component.ts
  goty-client/src/app/submission/info/info.component.scss
  goty-client/src/app/submission/list-item/list-item.component.scss
  goty-client/src/app/submission/submission.component.ts
Labels: frontend

#19 1.1.1 misc fixes
  goty-client/src/api/constants.ts
  goty-client/src/api/submission-flow/submission-flow.guard.ts
  goty-client/src/api/submission-flow/submission-flow.service.ts
  goty-client/src/api/submission-flow/submission-flow.store.ts
  goty-client/src/api/ui/ui.guard.ts
  goty-client/src/api/ui/ui.service.ts
  goty-client/src/api/ui/ui.store.ts
  goty-client/src/app/app-routing.module.ts
  goty-client/src/app/recovery/recovery.component.ts
  goty-client/src/app/results/results-summary/results-summary.component.html
  goty-client/src/app/results/results-table/results-table.component.html
  goty-client/src/app/start-page/start-page.component.ts
  goty-client/src/app/submission/giveaway/giveaway.component.html
  goty-client/src/app/submission/info/info.component.html
  goty-client/src/app/submission/info/info.component.scss
  goty-client/src/app/submission/info/info.component.ts
  goty-client/src/app/submission/list-item/list-item.component.html
  goty-client/src/app/submission/list-item/list-item.component.scss
  goty-client/src/app/submission/list-item/list-item.component.ts
  goty-client/src/app/submission/search-in-place/search-in-place.component.html
  goty-client/src/app/submission/submission.component.ts
Labels: bug, frontend
