Repository aleinin/game-of-the-year, pull requests merged in 2022-10, with the labels that each got.

#40 Update goty-server from Java 15 to Java 17. Update dependencies
  goty-server/Dockerfile
  goty-server/build.gradle.kts
  goty-server/gradle/wrapper/gradle-wrapper.jar
  goty-server/gradle/wrapper/gradle-wrapper.properties
  goty-server/gradlew
  goty-server/gradlew.bat
  goty-server/src/main/resources/application.yml
Labels: enhancement, backend

#41 Enable CI & fix smoke test
  .github/workflows/build.yaml
  goty-server/build.gradle.kts
  goty-server/src/main/kotlin/com/aleinin/goty/configuration/IGDBWrapperConfiguration.kt
  goty-server/src/main/kotlin/com/aleinin/goty/game/GameSearchClient.kt
  goty-server/src/main/kotlin/com/aleinin/goty/game/GameSearchConfiguration.kt
  goty-server/src/main/kotlin/com/aleinin/goty/game/GameSearchService.kt
  goty-server/src/main/kotlin/com/aleinin/goty/game/IGDBGameSearchClient.kt
  goty-server/src/main/kotlin/com/aleinin/goty/game/IGDBProperties.kt
  goty-server/src/main/resources/application.yml
  goty-server/src/test/kotlin/com/aleinin/goty/GameOfTheYearApplicationTests.kt
  goty-server/src/test/resources/application.yml
Labels: backend, refactor

#42 Configure local Gradle build cache and always publish Build Scan
  .github/workflows/build.yaml
  README.md
  goty-server/build.gradle.kts
  goty-server/gradle.properties
  goty-server/gradle/wrapper/gradle-wrapper.properties
Labels: backend

#44 Added tests to goty-server
  README.md
  goty-server/build.gradle.kts
  goty-server/src/main/kotlin/com/aleinin/goty/configuration/ObjectMapperConfiguration.kt
  goty-server/src/main/kotlin/com/aleinin/goty/game/GameSearchConfiguration.kt
  goty-server/src/main/kotlin/com/aleinin/goty/game/IGDBGameSearchClient.kt
  goty-server/src/main/kotlin/com/aleinin/goty/result/PointsService.kt
  goty-server/src/main/kotlin/com/aleinin/goty/submit/SubmissionController.kt
  goty-server/src/main/kotlin/com/aleinin/goty/submit/SubmissionRequest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/SubmissionDataHelper.kt
  goty-server/src/test/kotlin/com/aleinin/goty/game/GameControllerTest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/game/GameSearchServiceTest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/game/IGDBGameSearchClientTest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/result/GameRankingServiceTest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/result/GameScoringServiceTest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/result/PointsServiceTest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/result/ResultControllerTest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/result/ResultServiceTest.kt
  goty-server/src/test/kotlin/com/aleinin/goty/submit/SubmissionControllerTest.kt
Labels: documentation, backend, refactor
